#!/usr/bin/env bash
# Regenerate the binary Homebrew formula for the vjeantet/nono fork.
#
# Usage: ./update.sh <version>     (e.g. v0.65.1 or 0.65.1)
#
# Reads the release checksum manifest (SHA256SUMS.txt) produced by the Release
# workflow, extracts the sha256 of the two macOS artifacts, and writes a
# self-contained binary formula to $FORMULA_PATH.
#
# Environment:
#   SHA256SUMS_FILE  Path to the SHA256SUMS.txt downloaded from the release.
#                    Defaults to ./SHA256SUMS.txt.
#   FORMULA_PATH     Output path for the generated formula.
#                    Defaults to ./Formula/nono.rb.
#
# The published artifacts are named:
#   nono-v<ver>-aarch64-apple-darwin.tar.gz
#   nono-v<ver>-x86_64-apple-darwin.tar.gz
# and are downloaded from:
#   https://github.com/vjeantet/nono/releases/download/v<ver>/<artifact>

set -euo pipefail

[[ $# -ge 1 ]] || { echo "Usage: $0 <version>   (e.g. v0.65.1)" >&2; exit 1; }
ver="${1#v}"
[[ "$ver" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "Unexpected version: '${1}'" >&2; exit 1; }

sums="${SHA256SUMS_FILE:-./SHA256SUMS.txt}"
formula="${FORMULA_PATH:-./Formula/nono.rb}"

[[ -f "$sums" ]] || { echo "SHA256SUMS file not found: $sums" >&2; exit 1; }

arm_file="nono-v${ver}-aarch64-apple-darwin.tar.gz"
x86_file="nono-v${ver}-x86_64-apple-darwin.tar.gz"

# SHA256SUMS.txt lines are "<sha256>  <filename>" (filenames are flat, no path).
sha_arm="$(awk -v f="$arm_file" '$2 == f { print $1; exit }' "$sums")"
sha_x86="$(awk -v f="$x86_file" '$2 == f { print $1; exit }' "$sums")"

[[ -n "$sha_arm" ]] || { echo "sha256 not found for $arm_file in $sums" >&2; exit 1; }
[[ -n "$sha_x86" ]] || { echo "sha256 not found for $x86_file in $sums" >&2; exit 1; }

base_url="https://github.com/vjeantet/nono/releases/download/v${ver}"

mkdir -p "$(dirname "$formula")"
cat > "$formula" <<EOF
# This file is generated by packaging/homebrew/update.sh on each release.
# Do not edit by hand; changes will be overwritten.
class Nono < Formula
  desc "Kernel-enforced sandbox for AI agents, MCP servers and LLM workloads"
  homepage "https://github.com/vjeantet/nono"
  version "${ver}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${base_url}/${arm_file}"
      sha256 "${sha_arm}"
    end
    on_intel do
      url "${base_url}/${x86_file}"
      sha256 "${sha_x86}"
    end
  end

  def install
    bin.install "nono"
  end

  test do
    system "#{bin}/nono", "--version"
  end
end
EOF

echo "Wrote $formula for nono v${ver}"
